# Generated by Django 4.0.5 on 2022-06-29 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_questionviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionViews',
        ),
    ]
