# Generated by Django 4.0.5 on 2022-06-30 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_question_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='search',
        ),
    ]
