# Generated by Django 4.0.5 on 2022-06-30 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_question_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='categorie',
        ),
    ]
