# Generated by Django 4.0.5 on 2022-06-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_question_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='categorie',
        ),
        migrations.AlterField(
            model_name='question',
            name='questions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
