# Generated by Django 4.0.5 on 2022-06-30 14:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_remove_question_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questions',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
