# Generated by Django 4.0.5 on 2022-07-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_question_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
