# Generated by Django 4.0.5 on 2022-07-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0020_alter_question_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
