# Generated by Django 4.0.5 on 2022-07-01 16:52

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0020_alter_question_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questions',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
