# Generated by Django 4.0.5 on 2022-07-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0025_remove_question_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
