# Generated by Django 4.0.5 on 2022-08-07 15:31

from django.db import migrations
import django_editorjs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0026_question_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questions',
            field=django_editorjs.fields.EditorJsField(),
        ),
    ]
