# Generated by Django 4.0.5 on 2022-08-12 15:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0027_alter_question_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questions',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
