# Generated by Django 4.0.5 on 2022-07-14 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import projects.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(auto_created=True, max_length=200, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('thumbnail', models.ImageField(upload_to='projects/images')),
                ('uploaded_file', models.FileField(upload_to='', validators=[projects.validators.validate_file_extension], verbose_name='documents/%Y/%m/%d')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
