# Generated by Django 4.0.5 on 2022-07-26 08:25

from django.db import migrations, models
import projects.validators


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projects_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='uploaded_file',
            field=models.FileField(upload_to='', validators=[projects.validators.validate_file_extension], verbose_name='projects/documents/%Y/%m/%d'),
        ),
    ]
