# Generated by Django 4.0.5 on 2022-06-10 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employe_details',
            old_name='update_on',
            new_name='added_on',
        ),
    ]
