# Generated by Django 4.0.5 on 2022-06-10 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_employe_details_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe_details',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
