# Generated by Django 4.0.5 on 2022-06-10 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_employe_details_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe_details',
            name='slug',
        ),
    ]
