# Generated by Django 4.0.5 on 2022-06-27 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_employe_details_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employe_details',
        ),
    ]
