# Generated by Django 4.0.5 on 2022-06-27 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_newsletter_email_alter_newsletter_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='name',
            new_name='username',
        ),
    ]
