# Generated by Django 4.0.5 on 2022-06-28 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_category_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='blog',
        ),
    ]
