# Generated by Django 4.0.5 on 2022-07-02 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_blog_author_delete_category_delete_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='subscribed_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
