# Generated by Django 4.0.5 on 2022-07-11 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_profileupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profileupdate',
        ),
    ]
