# Generated by Django 4.0.5 on 2022-07-11 14:19

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_delete_profileupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='profileupdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', djrichtextfield.models.RichTextField()),
            ],
        ),
    ]
