# Generated by Django 4.0.5 on 2022-07-12 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
