# Generated by Django 4.0.5 on 2022-07-06 13:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_category_options_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='article',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
