# Generated by Django 4.0.5 on 2022-07-06 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_blog_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
    ]
