# Generated by Django 4.0.5 on 2022-07-22 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_blog_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='featured',
            new_name='is_active',
        ),
    ]
