# Generated by Django 4.0.5 on 2022-08-18 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_blog_bookmarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='bookmarks',
        ),
    ]
