# Generated by Django 4.0.5 on 2022-08-18 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_alter_blog_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='likes',
        ),
    ]
